### ISSUE TITLE
希望能建一个基于时序预测的分支

### ISSUE THREAD

**Issue by chenjw505** [rwbfd/OpenCompetitionV2#1]
1. 可以列一些经典的时序预测比赛，相关数据集，top方案；
   
2. 贴一些相关的经典的和最新的文献

3. 还可以贴一些正在进行的相关比赛，能用该项目哪个模型做baseline，学以致用啊。

基本上这个方向赛道就可以慢慢积累的，不管是对大家比赛，写论文还是工作落地都很有帮助！

ps: 感谢感谢

**Comment by rwbfd** [comment]
1. 这个项目还是希望提供一个统一的接口，所以应该不会直接直接复制代码。
2. 会考虑增加时间序列的一些功能，例如特征提取器等。
3. 如果您发现一些有趣的比较，也特别欢迎提供。我们会找到这里面比较有用的部分进行处理。
